#! /bin/bash

FILE="cmd.php"
RED=$(tput setaf 1)
RESET=$(tput sgr0)

runCommand() {
    php $1 $2
}

if [ -f $FILE ]; then
    runCommand $FILE $@
elif [[ $XENFORO_PATH ]]; then
    if [ -f $XENFORO_PATH/$FILE ]; then
        runCommand $XENFORO_PATH/$FILE $@
    else
        echo -e "${RED} XENFORO_PATH is not a valid XenForo 2 directory.${RESET}"
    fi
else
    echo -e "${RED} It does not appear you are in a valid XenForo 2 directory.${RESET}"
fi
